config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'

  resources :brands, only: %i[index show]
  resources :products, only: %i[index show]
  get "users/:id", to: "users#show", as: :user
  get "cheques", to: "cheques#cheque", as: :cheque

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/brand.rb
class Brand < ApplicationRecord
  has_many :products
end

app/models/cheque.rb
class Cheque < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :brand
  has_many :cheques
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  PROVINCES = ['CABA', 'Buenos Aires','Córdoba', 'Mendoza', 'Salta', 'Santa Fe', 'Tucumán']

  validates :province, inclusion: { in: PROVINCES }
  validates :registration_number, length: { is: 6 }, presence: true
  validates :first_name, presence: true
  validates :first_name, length: { in: 2..20 }, allow_blank: true
  validates :last_name, presence: true
  validates :last_name, length: { in: 2..20 }, allow_blank: true

  has_many :cheques, dependent: :destroy

  validate :registration_number_uniqueness
    def national?
      province == 'CABA'
  end

  private

  def registration_number_uniqueness
    users = User.where(registration_number: registration_number)  # users con el mismo registration number
    # [User[registration_number: 1, province: "CABA"], User[registration_number: 1, province: "Cordoba"]]
    repetido = users.any? { |user| user.national? == national? }
    errors.add(:registration_number, "ta shepetido") if repetido
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :province, :registration_number])
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  def after_sign_in_path_for(resource)
    user_path(resource)
  end
end

app/controllers/brands_controller.rb
class BrandsController < ApplicationController

  def index
    @brands = Brand.all
  end


  def show
    @brand = Brand.find(params[:id])
  end

end

app/controllers/cheques_controller.rb
class ChequesController < ApplicationController

  def cheque
    @user = current_user
      respond_to do |format|
        format.html
        format.pdf do
         pdf = render_to_string(pdf: "cheques/cheque.pdf.erb", template: "cheques/cheque.pdf.erb", layout: "pdf.html", background: true)
         send_data pdf, filename: 'report.pdf', type: 'application/pdf'
        end
      end
    end

    def numero_de_cheque
    end
  end
  # def cheque
  #   pdf = WickedPdf.new.pdf_from_string(
  #   render_to_string(
  #   template: "cheques/cheque.pdf.erb",
  #   layout: "pdf.html"))
  #   send_data(pdf,
  #   filename: "file_name.pdf",
  #   type: "application/pdf",
  #   disposition: "attachment")
  #   end
  # end

app/controllers/pages_controller.rb
# frozen_string_literal: true

class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home, :show]

  def home
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    @products = Product.all
  end

  def show
    @product = Product.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def show
    @user = User.find(params[:id])
    @brands = Brand.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/brands/show.html.erb
<div class="container">
  <div class="row col-12 justify-content-center">
    <div class="text-center  border border-ligth w-100  shadow-sm p-3 mb-5 bg-white rounded ">
      <h1>Products</h1>
        <div class="table-responsive">
          <table class="table">
            <thead class="thead-dark">
              <tr>
                <th scope="col">Products</th>
                <th><%= link_to "Volver", user_path(current_user), class: "btn btn-primary" %></th>
              </tr>
              </thead>
              <tbody>
                <% @brand.products.each do |product| %>
                <tr>
                    <td><%= image_tag product.name, size: "100" %></td>
                    <td><%= link_to "Emitir cheque", cheque_path(format: "pdf"), class: "btn btn-success" %></td>
                  </tr>
                  </th>

                    <% end %>
                </tbody>
            </table>
          </div>
    </div>
  </div>
</div>

app/views/cheques/cheque.pdf.erb
<div class="cheque-background">
  <div class="container">
    <style>4567789654</style>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdontoCheque</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
  <link rel="stylesheet" href="pdf.scss">
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag wicked_pdf_asset_base64("sensodyne/odontocheque-frente-sensodyne.jpg") %>
  <style>
      .absolute{ position: absolute }
      .fecha{bottom: 130px; left: 200px; }
      .numero_cheque{ top: 220px; right: 300px; }
      .datos_personales{ bottom: 60px; right: 160px; }
      .estilos{ font-size: 40px;}
      .estilo_datos{ font-size: 25px;}
  </style>
</head>
<body>
  <div class="cheque-background">
    <p class="numero_cheque estilos absolute">15425785 </p>
    <p class="fecha  estilo_datos absolute"><%= Time.now.strftime("%F")%></p>
    <div class="datos_personales estilo_datos absolute">
      <ul style="list-style-type: none">
        <li><%=@user.first_name.capitalize %> <%=@user.last_name.capitalize %></li>
        <li><%=@user.registration_number %></li>
        <li><%=@user.province.capitalize %></li>
      </ul>
    </div>
    <%= image_tag wicked_pdf_asset_base64("sensodyne/odontocheque-frente-sensodyne.jpg") %>
  </div>
  <%= yield %>
</body>
</html>

app/views/pages/home.html.erb
<div class="container my-5 py-5 ">
  <div class="row col-12 justify-content-center">
  <div class="text-center borde border border-ligth w-50  shadow-sm p-3 mb-5 bg-white rounded">
          <h1>Odonto Cheque</h1>
            <h2>Bienvenido</h2>
            <p>Selececcione la opcion que desea realizar </p>
            <div class="my-2 ">
              <%= link_to "Iniciar Sesión", new_user_session_path, class: "btn btn-primary" %>
              <%= link_to "Registrarse", new_user_registration_path, class: "btn btn-warning" %>
            </div>
    </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/users/show.html.erb
<div class="container my-5 py-5 ">
  <div class="row col-12 justify-content-center">
    <div class="d-flex">
        <div class="text-center border border-ligth w-50  shadow-sm p-lg-3 mb-lg-5 bg-white rounded">
          <h1> Bienvenido <%= @user.username.capitalize %></h1>
          <h3><%=@user.first_name.capitalize %> <%=@user.last_name.capitalize %></h3>
          <p>Matricula número : <%=@user.registration_number %></p>
          <p><%=@user.province.capitalize %></p>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
        </div>
        <div class="mx-lg-5  border border-ligth w-50  shadow-sm p-lg-3 mb-lg-5 bg-white rounded">
        <div>
          <h2 class="text-center mb-5">Elija una marca</h2>
        </div>
        <div class="d-flex justify-content-center align-items-center">
        <% @brands.each do |brand| %>
            <span class="mx-4">
              <%= link_to "#{image_tag brand.name, size: "100x60"}".html_safe, brand_path(brand.id) %>
            </span>
             <% end %>
        </div>
    </div>
  </div>
</div>